field: adb2aa1d-2011-4c34-95bf-1407968683ed
fieldLayouts:
  1561abb0-ed4d-43b0-a02b-50261f1a1997:
    tabs:
      -
        elements:
          -
            fieldUid: 0c7c5205-c910-4822-ae32-7073bac8ec5f
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4448d24b-d0ba-4381-b009-e9df38e0cdb1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0c7c5205-c910-4822-ae32-7073bac8ec5f:
    contentColumnType: string
    fieldGroup: null
    handle: file
    instructions: ''
    name: File
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:f7ab9d53-c46f-47d9-87b4-ec5d28d3dce8'
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:f7ab9d53-c46f-47d9-87b4-ec5d28d3dce8'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  4448d24b-d0ba-4381-b009-e9df38e0cdb1:
    contentColumnType: string
    fieldGroup: null
    handle: imageStyle
    instructions: ''
    name: 'Image Style'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - 'Full Width'
            -
              - value
              - fullWidth
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Grid
            -
              - value
              - grid
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: image
name: Image
sortOrder: 1
