contentColumnType: string
fieldGroup: d19d3240-1b50-4de3-9938-2a3ead6cc468
handle: pageContent
instructions: ''
name: 'Page Content'
searchable: false
settings:
  contentTable: '{{%matrixcontent_pagecontent}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
