contentColumnType: text
fieldGroup: d19d3240-1b50-4de3-9938-2a3ead6cc468
handle: pageTitle
instructions: ''
name: 'Page Title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
