enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  9d163d3e-5e8b-443f-8a10-0bfb4d64e698:
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
